/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefinirMotDePasseRouteImport } from './routes/definir-mot-de-passe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSondagesRouteImport } from './routes/_authenticated/sondages'
import { Route as AuthenticatedRecommandationsRouteImport } from './routes/_authenticated/recommandations'
import { Route as AuthenticatedMonProfilRouteImport } from './routes/_authenticated/mon-profil'
import { Route as AuthenticatedMembresRouteImport } from './routes/_authenticated/membres'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedEvenementsRouteImport } from './routes/_authenticated/evenements'
import { Route as AuthenticatedAdminRappelRouteImport } from './routes/_authenticated/admin-rappel'
import { Route as AuthenticatedPresencesIndexRouteImport } from './routes/_authenticated/presences/index'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes/index'
import { Route as AuthenticatedDemandesNouvelleRouteImport } from './routes/_authenticated/demandes/nouvelle'
import { Route as AuthenticatedDemandesDemandeIdRouteImport } from './routes/_authenticated/demandes/$demandeId'

const DefinirMotDePasseRoute = DefinirMotDePasseRouteImport.update({
  id: '/definir-mot-de-passe',
  path: '/definir-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSondagesRoute = AuthenticatedSondagesRouteImport.update({
  id: '/sondages',
  path: '/sondages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommandationsRoute =
  AuthenticatedRecommandationsRouteImport.update({
    id: '/recommandations',
    path: '/recommandations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonProfilRoute = AuthenticatedMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembresRoute = AuthenticatedMembresRouteImport.update({
  id: '/membres',
  path: '/membres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvenementsRoute = AuthenticatedEvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRappelRoute =
  AuthenticatedAdminRappelRouteImport.update({
    id: '/admin-rappel',
    path: '/admin-rappel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresencesIndexRoute =
  AuthenticatedPresencesIndexRouteImport.update({
    id: '/presences/',
    path: '/presences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesNouvelleRoute =
  AuthenticatedDemandesNouvelleRouteImport.update({
    id: '/demandes/nouvelle',
    path: '/demandes/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesDemandeIdRoute =
  AuthenticatedDemandesDemandeIdRouteImport.update({
    id: '/demandes/$demandeId',
    path: '/demandes/$demandeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/admin-rappel': typeof AuthenticatedAdminRappelRoute
  '/evenements': typeof AuthenticatedEvenementsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/membres': typeof AuthenticatedMembresRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/sondages': typeof AuthenticatedSondagesRoute
  '/demandes/$demandeId': typeof AuthenticatedDemandesDemandeIdRoute
  '/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/presences/': typeof AuthenticatedPresencesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/admin-rappel': typeof AuthenticatedAdminRappelRoute
  '/evenements': typeof AuthenticatedEvenementsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/membres': typeof AuthenticatedMembresRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/sondages': typeof AuthenticatedSondagesRoute
  '/': typeof AuthenticatedIndexRoute
  '/demandes/$demandeId': typeof AuthenticatedDemandesDemandeIdRoute
  '/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
  '/presences': typeof AuthenticatedPresencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-mot-de-passe': typeof DefinirMotDePasseRoute
  '/_authenticated/admin-rappel': typeof AuthenticatedAdminRappelRoute
  '/_authenticated/evenements': typeof AuthenticatedEvenementsRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/membres': typeof AuthenticatedMembresRoute
  '/_authenticated/mon-profil': typeof AuthenticatedMonProfilRoute
  '/_authenticated/recommandations': typeof AuthenticatedRecommandationsRoute
  '/_authenticated/sondages': typeof AuthenticatedSondagesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/demandes/$demandeId': typeof AuthenticatedDemandesDemandeIdRoute
  '/_authenticated/demandes/nouvelle': typeof AuthenticatedDemandesNouvelleRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/_authenticated/presences/': typeof AuthenticatedPresencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/definir-mot-de-passe'
    | '/admin-rappel'
    | '/evenements'
    | '/invites'
    | '/membres'
    | '/mon-profil'
    | '/recommandations'
    | '/sondages'
    | '/demandes/$demandeId'
    | '/demandes/nouvelle'
    | '/demandes/'
    | '/presences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/definir-mot-de-passe'
    | '/admin-rappel'
    | '/evenements'
    | '/invites'
    | '/membres'
    | '/mon-profil'
    | '/recommandations'
    | '/sondages'
    | '/'
    | '/demandes/$demandeId'
    | '/demandes/nouvelle'
    | '/demandes'
    | '/presences'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/definir-mot-de-passe'
    | '/_authenticated/admin-rappel'
    | '/_authenticated/evenements'
    | '/_authenticated/invites'
    | '/_authenticated/membres'
    | '/_authenticated/mon-profil'
    | '/_authenticated/recommandations'
    | '/_authenticated/sondages'
    | '/_authenticated/'
    | '/_authenticated/demandes/$demandeId'
    | '/_authenticated/demandes/nouvelle'
    | '/_authenticated/demandes/'
    | '/_authenticated/presences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirMotDePasseRoute: typeof DefinirMotDePasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/definir-mot-de-passe': {
      id: '/definir-mot-de-passe'
      path: '/definir-mot-de-passe'
      fullPath: '/definir-mot-de-passe'
      preLoaderRoute: typeof DefinirMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sondages': {
      id: '/_authenticated/sondages'
      path: '/sondages'
      fullPath: '/sondages'
      preLoaderRoute: typeof AuthenticatedSondagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommandations': {
      id: '/_authenticated/recommandations'
      path: '/recommandations'
      fullPath: '/recommandations'
      preLoaderRoute: typeof AuthenticatedRecommandationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-profil': {
      id: '/_authenticated/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AuthenticatedMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membres': {
      id: '/_authenticated/membres'
      path: '/membres'
      fullPath: '/membres'
      preLoaderRoute: typeof AuthenticatedMembresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evenements': {
      id: '/_authenticated/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof AuthenticatedEvenementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-rappel': {
      id: '/_authenticated/admin-rappel'
      path: '/admin-rappel'
      fullPath: '/admin-rappel'
      preLoaderRoute: typeof AuthenticatedAdminRappelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presences/': {
      id: '/_authenticated/presences/'
      path: '/presences'
      fullPath: '/presences/'
      preLoaderRoute: typeof AuthenticatedPresencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/nouvelle': {
      id: '/_authenticated/demandes/nouvelle'
      path: '/demandes/nouvelle'
      fullPath: '/demandes/nouvelle'
      preLoaderRoute: typeof AuthenticatedDemandesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/$demandeId': {
      id: '/_authenticated/demandes/$demandeId'
      path: '/demandes/$demandeId'
      fullPath: '/demandes/$demandeId'
      preLoaderRoute: typeof AuthenticatedDemandesDemandeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRappelRoute: typeof AuthenticatedAdminRappelRoute
  AuthenticatedEvenementsRoute: typeof AuthenticatedEvenementsRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedMembresRoute: typeof AuthenticatedMembresRoute
  AuthenticatedMonProfilRoute: typeof AuthenticatedMonProfilRoute
  AuthenticatedRecommandationsRoute: typeof AuthenticatedRecommandationsRoute
  AuthenticatedSondagesRoute: typeof AuthenticatedSondagesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemandesDemandeIdRoute: typeof AuthenticatedDemandesDemandeIdRoute
  AuthenticatedDemandesNouvelleRoute: typeof AuthenticatedDemandesNouvelleRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
  AuthenticatedPresencesIndexRoute: typeof AuthenticatedPresencesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRappelRoute: AuthenticatedAdminRappelRoute,
  AuthenticatedEvenementsRoute: AuthenticatedEvenementsRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedMembresRoute: AuthenticatedMembresRoute,
  AuthenticatedMonProfilRoute: AuthenticatedMonProfilRoute,
  AuthenticatedRecommandationsRoute: AuthenticatedRecommandationsRoute,
  AuthenticatedSondagesRoute: AuthenticatedSondagesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemandesDemandeIdRoute: AuthenticatedDemandesDemandeIdRoute,
  AuthenticatedDemandesNouvelleRoute: AuthenticatedDemandesNouvelleRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
  AuthenticatedPresencesIndexRoute: AuthenticatedPresencesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirMotDePasseRoute: DefinirMotDePasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
