/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSondagesRouteImport } from './routes/_authenticated/sondages'
import { Route as AuthenticatedRecommandationsRouteImport } from './routes/_authenticated/recommandations'
import { Route as AuthenticatedMembresRouteImport } from './routes/_authenticated/membres'
import { Route as AuthenticatedEvenementsRouteImport } from './routes/_authenticated/evenements'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSondagesRoute = AuthenticatedSondagesRouteImport.update({
  id: '/sondages',
  path: '/sondages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommandationsRoute =
  AuthenticatedRecommandationsRouteImport.update({
    id: '/recommandations',
    path: '/recommandations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembresRoute = AuthenticatedMembresRouteImport.update({
  id: '/membres',
  path: '/membres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvenementsRoute = AuthenticatedEvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/evenements': typeof AuthenticatedEvenementsRoute
  '/membres': typeof AuthenticatedMembresRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/sondages': typeof AuthenticatedSondagesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/evenements': typeof AuthenticatedEvenementsRoute
  '/membres': typeof AuthenticatedMembresRoute
  '/recommandations': typeof AuthenticatedRecommandationsRoute
  '/sondages': typeof AuthenticatedSondagesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/evenements': typeof AuthenticatedEvenementsRoute
  '/_authenticated/membres': typeof AuthenticatedMembresRoute
  '/_authenticated/recommandations': typeof AuthenticatedRecommandationsRoute
  '/_authenticated/sondages': typeof AuthenticatedSondagesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/evenements'
    | '/membres'
    | '/recommandations'
    | '/sondages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/evenements'
    | '/membres'
    | '/recommandations'
    | '/sondages'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/evenements'
    | '/_authenticated/membres'
    | '/_authenticated/recommandations'
    | '/_authenticated/sondages'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sondages': {
      id: '/_authenticated/sondages'
      path: '/sondages'
      fullPath: '/sondages'
      preLoaderRoute: typeof AuthenticatedSondagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommandations': {
      id: '/_authenticated/recommandations'
      path: '/recommandations'
      fullPath: '/recommandations'
      preLoaderRoute: typeof AuthenticatedRecommandationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membres': {
      id: '/_authenticated/membres'
      path: '/membres'
      fullPath: '/membres'
      preLoaderRoute: typeof AuthenticatedMembresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evenements': {
      id: '/_authenticated/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof AuthenticatedEvenementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEvenementsRoute: typeof AuthenticatedEvenementsRoute
  AuthenticatedMembresRoute: typeof AuthenticatedMembresRoute
  AuthenticatedRecommandationsRoute: typeof AuthenticatedRecommandationsRoute
  AuthenticatedSondagesRoute: typeof AuthenticatedSondagesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEvenementsRoute: AuthenticatedEvenementsRoute,
  AuthenticatedMembresRoute: AuthenticatedMembresRoute,
  AuthenticatedRecommandationsRoute: AuthenticatedRecommandationsRoute,
  AuthenticatedSondagesRoute: AuthenticatedSondagesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
